# https://medium.com/@yusufbiyik/useful-github-actions-discord-webhooks-6e356751d954
name: Webhook on Event
# Make sure to change what triggers your action based on your needs
on: [milestone, create, delete, fork, issues, member, pull_request, pull_request_review, issue_comment, push]
jobs:
  # ID of our job
  webhook-request:
    # OS to run our job on
    runs-on: ubuntu-latest
    steps:
    - name: Send a request to webhook
      run: |
        RESPONSE=$(curl -H "Content-Type: application/json" -X POST -d '{
        "username": "GitHub Dev Tree",
        "content": "@ClariQ",
        "embeds": [
          {
            "type": "rich",
            "title": "ClariQ Dev Build Update",
            "description": "New changes on ClariQ Dev Build Update repository by ${{ github.actor }}",
            "color": ff5557,
            "thumbnail": {
              "url": "https://cdn.discordapp.com/icons/638026397650255912/7ca39fba389cd228fe0b800cae41436f.webp"
            },
            "author": {
              "name": "${{ github.actor }}",
              "url": "https://github.com/${{ github.actor_id }}",
              "icon_url": "https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4"
            },
            "url": "https://github.com/NvexxNL/ClariQ/tree/dev"
          }
        ]
        }' ${{ secrets.WEBHOOK_URL }})
        echo "Webhook server response: $RESPONSE"
